import React, { useState } from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';

const products = [
    {
        id: 1,
        col1: 'abcasdasd',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 2,

        col1: 'bca',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 3,
        col1: 'cab',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 4,
        col1: 'def',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 5,
        col1: 'efg',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 6,
        col1: 'hij',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "35",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",

    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 7,
        name: "Yoga mat",
        price: "₦15,000",
        category: "Fitness",
        quantity: "15",
        rating: "4",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 2,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 3,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 4,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 5,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 6,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 7,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col12: "asdfghijklop",
    },
    {
        id: 8,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'abc',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'yza',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'vwx',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 9,
        col1: 'stu',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },
    {
        id: 10,
        col1: 'pqr',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    }, {
        id: 1,
        col1: 'mno',
        col2: "Apple Watch",
        col3: "350,000",
        col4: "Accessories",
        col5: "7",
        col6: "xyz",
        col7: "abc",
        col8: "1233",
        col9: "qwerty",
        col10: "abc",
        col11: "asdfgh",
        col12: "qwerty",
        col13: "asdfghijklop",
    },

];

const columns = [
    {
        field: "col1", header: 'Line'
    },
    { field: "col2", header: "Loop", },
    { field: "col3", header: "PKG Line", },
    { field: "col4", header: "Type" },
    { field: "col5", header: "Flavour Desc" },
    { field: "col6", header: "Sch. Material Code" },
    { field: "col7", header: "Scanned Material Code" },
    {
        field: "col8", header: "Override"
    },
    {
        field: "col9", header: "Bypass"

    },
    {
        field: "col10", header: "COMode"
    },
    {
        field: "col11", header: "Fault"
    },
    { field: "col12", header: "Cable Status" },
    { field: "col13", header: "WB Recovery" },

];


const DataGridReactPrime = () => {
    const [sizeOptions] = useState([
        { label: 'Small', value: 'small' },
        { label: 'Normal', value: 'normal' },
        { label: 'Large', value: 'large' }
    ]);

    const paginatorLeft = <Button type="button" icon="pi pi-refresh" text />;
    const paginatorRight = <Button type="button" icon="pi pi-download" text />;

    const [first, setFirst] = useState(0);
    const [rows, setRows] = useState(10);

    const onPageChange = (event) => {
        setFirst(event.first);
        setRows(event.rows);
    };
    const ratingBodyTemplate = (rowData) => {
        return <p style={{ fontSize: 20 }}>{rowData.col1}</p>;
    };

    return (
        <div className="card" style={{ width: '88%', marginLeft: 15 }}>
            <DataTable
                value={products}
                tableStyle={{ minWidth: '50rem' }}
                removableSort
                scrollable
                scrollHeight="450px"
                resizableColumns
                stripedRows
                // pagination
                paginator
                rows={10}
                rowsPerPageOptions={[10, 25, 50]}
                currentPageReportTemplate="{first} to {last} of {totalRecords}"

                paginatorTemplate="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown"

                // pagination end
                size="small"
            >
                {columns.map((col, i) => (
                    <Column key={col.field} field={col.field} header={col.header} sortable
                    // body={col.field == 'col1'? ratingBodyTemplate:null}
                    />
                ))}
            </DataTable>
            {/* <div>
                <Paginator first={first} rows={rows} totalRecords={120} rowsPerPageOptions={[10, 20, 30]} onPageChange={onPageChange} />
            </div> */}
        </div>
    );
}

export default DataGridReactPrime;